### ISSUE TITLE
ImportError: cannot import name 'SecureProxySession' from 'requests_httpsproxy' 

### ISSUE THREAD

**Issue by invertednz** [phuslu/requests_httpsproxy#4]
import requests_httpsproxy
from requests_httpsproxy import SecureProxySession

Receiving the following error on the line above:

Traceback (most recent call last):
  File "RunTestsWithAppsurifyTest2.py", line 18, in <module>
    from requests_httpsproxy import SecureProxySession
ImportError: cannot import name 'SecureProxySession' from 'requests_httpsproxy' (C:\Users\james\AppData\Local\Programs\Python\Python37\lib\site-packages\requests_httpsproxy\__init__.py)

If I don't use 'from requests_httpsproxy import SecureProxySession'
and instead use
with requests_httpsproxy.SecureProxySession() as s:
                s.verify = False
                response = s.get(apiurl, headers=headers, data=payload, files=files, proxies={'http':https_proxy, 'https':https_proxy})
     
I get the following error
AttributeError: module 'requests_httpsproxy' has no attribute 'SecureProxySession'

**Comment by phuslu** [comment]
please see latest requsts, the underlying urllib3 already support https proxy. so closes this issue.
will archive this project soon.
